# frontend-deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: yolo-client-deployment
  namespace: default
  labels:
    app: yolo-client
spec:
  replicas: 2
  selector:
    matchLabels:
      app: yolo-client
  template:
    metadata:
      labels:
        app: yolo-client
    spec:
      containers:
        - name: yolo-client
          image: docker.io/edwinkorir38/yolo-client:v1.0.3
          ports:
            - containerPort: 80
          env:
            - name: REACT_APP_API_URL
              value: "http://yolo-backend-service:5000/api"
