# frontend-deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: yolo-client-deployment
  labels:
    app: yolo-client
spec:
  replicas: 2
  selector:
    matchLabels:
      app: yolo-client
  template:
    metadata:
      labels:
        app: yolo-client
    spec:
      containers:
        - name: yolo-client
          image: edwinkorir38/yolo-client:v1.0.1
          ports:
            - containerPort: 3000
          env:
            - name: REACT_APP_API_URL
              value: "http://yolo-backend:5000/api"

